from .registry import Registry


SAMPLING_METHODS = Registry("SAMPLING_METHODS")
ASYNC_SAMPLING_METHODS = Registry("ASYNC_SAMPLING_METHODS")
POSTPROCESS_METHODS = Registry("POSTPROCESS_METHODS")
INFERENCE_METHODS = Registry("INFERENCE_METHODS")
